import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {createDocument,createNode,type MeshPayload} from '@formforge/model'
import {useEditor} from './editor'
import {geometryClient} from '@/geometry/client'
import {saveProject} from '@/lib/db'
vi.mock('@/geometry/client',()=>({geometryClient:{evaluate:vi.fn(),cancel:vi.fn()}}))
vi.mock('@/lib/db',()=>({saveProject:vi.fn(async()=>undefined),loadMostRecentProject:vi.fn(),deleteProject:vi.fn()}))
const mesh:MeshPayload={positions:new Float32Array([0,0,0,1,0,0,0,1,0]),indices:new Uint32Array([0,1,2]),triangleCount:1,volume:0}
beforeEach(()=>{vi.useFakeTimers();vi.clearAllMocks();const doc={...createDocument(),nodes:[createNode('box')]};useEditor.setState({document:doc,meshDocument:doc,mesh,undoStack:[],redoStack:[],placingNodeId:null,geometryStatus:'ready',buildMode:'automatic',selectedNodeIds:[doc.nodes[0]!.id],selectedNodeId:doc.nodes[0]!.id});vi.mocked(geometryClient.evaluate).mockResolvedValue(mesh)})
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers()})
it('defers expensive edits in manual mode while saving the editable document',async()=>{useEditor.getState().setBuildMode('manual');const n=useEditor.getState().document.nodes[0]!;useEditor.getState().updateNode(n.id,{parameters:{...n.parameters,width:45}});await vi.advanceTimersByTimeAsync(2000);expect(geometryClient.evaluate).not.toHaveBeenCalled();expect(saveProject).toHaveBeenCalled();expect(useEditor.getState().meshDocument).not.toBe(useEditor.getState().document);await useEditor.getState().rebuild();expect(useEditor.getState().meshDocument).toBe(useEditor.getState().document)})
it('cancels a queued build and resumes latest geometry when automatic is restored',async()=>{const n=useEditor.getState().document.nodes[0]!;useEditor.getState().updateNode(n.id,{parameters:{...n.parameters,width:45}});useEditor.getState().setBuildMode('manual');await vi.advanceTimersByTimeAsync(200);expect(geometryClient.evaluate).not.toHaveBeenCalled();useEditor.getState().setBuildMode('automatic');await vi.advanceTimersByTimeAsync(200);expect(geometryClient.evaluate).toHaveBeenCalledTimes(1);expect(useEditor.getState().meshDocument).toBe(useEditor.getState().document)})
it('resets manual mode on project replacement',()=>{useEditor.getState().setBuildMode('manual');useEditor.getState().newDocument();expect(useEditor.getState().buildMode).toBe('automatic')})
it('jumps across multiple edits in one build and preserves redo',async()=>{const original=useEditor.getState().document,n=original.nodes[0]!;for(const name of ['A','B','C'])useEditor.getState().updateNode(n.id,{name});useEditor.getState().jumpHistory(0);expect(useEditor.getState().document).toBe(original);expect(useEditor.getState().redoStack).toHaveLength(3);await vi.advanceTimersByTimeAsync(200);expect(geometryClient.evaluate).toHaveBeenCalledTimes(1);useEditor.getState().jumpHistory(3);expect(useEditor.getState().document.nodes[0]!.name).toBe('C');expect(useEditor.getState().redoStack).toHaveLength(0)})
it('refuses a history jump during placement without losing the draft',()=>{const before=useEditor.getState().document;useEditor.setState({placingNodeId:before.nodes[0]!.id});useEditor.getState().jumpHistory(0);expect(useEditor.getState().document).toBe(before);expect(useEditor.getState().notice).toMatch(/place|placement/i)})
it('ignores an active build that finishes after manual mode cancels it',async()=>{let finish!:(mesh:MeshPayload)=>void;vi.mocked(geometryClient.evaluate).mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve}));const old=useEditor.getState().meshDocument,build=useEditor.getState().rebuild();useEditor.getState().setBuildMode('manual');expect(geometryClient.cancel).toHaveBeenCalled();const n=useEditor.getState().document.nodes[0]!;useEditor.getState().updateNode(n.id,{parameters:{...n.parameters,width:55}});finish(mesh);await build;expect(useEditor.getState().meshDocument).toBe(old);expect(useEditor.getState().geometryStatus).toBe('idle')})
it('clears future history only after a new edit',()=>{const n=useEditor.getState().document.nodes[0]!;useEditor.getState().updateNode(n.id,{name:'A'});useEditor.getState().updateNode(n.id,{name:'B'});useEditor.getState().jumpHistory(0);expect(useEditor.getState().redoStack).toHaveLength(2);useEditor.getState().updateNode(n.id,{name:'Different path'});expect(useEditor.getState().redoStack).toHaveLength(0)})
it('requires a current preview before a new manual-mode sculpt stroke but permits continuation stamps',()=>{useEditor.getState().setBuildMode('manual');const stamp=(remember=true)=>useEditor.getState().addSculptStroke({x:0,y:0,z:0},'add',2,.5,'smooth',{x:0,y:0,z:1},remember);stamp();expect(useEditor.getState().document.sculptStrokes).toHaveLength(1);stamp(false);expect(useEditor.getState().document.sculptStrokes).toHaveLength(2);stamp();expect(useEditor.getState().document.sculptStrokes).toHaveLength(2);expect(useEditor.getState().notice).toContain('Rebuild')})
