import {useState} from 'react'
import {useEditor} from '@/store/editor'
import {NumberInput} from './NumberInput'
import {patternAssembly,translateAssembly,meshBounds,movableSelection} from '@/lib/assemblyTools'
import {createExportDocument} from '@/lib/exportScope'
import {evaluateSnapshot} from '@/geometry/evaluateSnapshot'
export function AssemblyToolsPanel(){
 const doc=useEditor(s=>s.document),ids=useEditor(s=>s.selectedNodeIds),[axis,setAxis]=useState<'x'|'y'|'z'>('x'),[mode,setMode]=useState<'linear'|'polar'>('linear'),[count,setCount]=useState(3),[spacing,setSpacing]=useState(30),[degrees,setDegrees]=useState(360),[origin,setOrigin]=useState({x:0,y:0,z:0}),[anchor,setAnchor]=useState(''),[gap,setGap]=useState(0),[side,setSide]=useState('after'),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 return <section className="workflow-card"><h3>Arrange an assembly</h3><p>{ids.length} selected shapes. Combined and inserted assemblies stay together.</p><label className="cad-select-label">Axis<select value={axis} onChange={e=>setAxis(e.target.value as typeof axis)}>{['x','y','z'].map(a=><option key={a} value={a}>{a.toUpperCase()}</option>)}</select></label>
 <h4>Repeat selection</h4><label className="cad-select-label">Pattern<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="linear">Linear</option><option value="polar">Polar around origin</option></select></label><NumberInput label="Instances including original" value={count} onChange={setCount}/>{mode==='linear'?<NumberInput label="Instance spacing" suffix="mm" value={spacing} onChange={setSpacing}/>:<><NumberInput label="Sweep angle" suffix="°" value={degrees} onChange={setDegrees}/><p>Pattern origin</p><div className="size-fields">{(['x','y','z'] as const).map(a=><NumberInput key={a} label={`Origin ${a.toUpperCase()}`} suffix="mm" value={origin[a]} onChange={v=>setOrigin({...origin,[a]:v})}/>)}</div></>}
 <button className="workflow-action" disabled={!ids.length||busy} onClick={()=>{try{const s=useEditor.getState();s.dispatch({type:'replace-document',document:patternAssembly(s.document,s.selectedNodeIds,{mode,axis,count,spacing,degrees,origin})});setError('');s.setNotice('Assembly copies created. Dimension formulas remain shared; each copy can be moved independently.')}catch(e){setError((e as Error).message)}}}>Create assembly pattern</button>
 <h4>Align with a gap</h4><label className="cad-select-label">Reference shape<select value={anchor} onChange={e=>setAnchor(e.target.value)}><option value="">Choose reference</option>{doc.nodes.filter(n=>n.boolean==='add'&&!n.suppressed).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label className="cad-select-label">Place selection<select value={side} onChange={e=>setSide(e.target.value)}><option value="after">After reference maximum</option><option value="before">Before reference minimum</option></select></label><NumberInput label="Gap (negative overlaps)" suffix="mm" value={gap} onChange={setGap}/><p>Aligns evaluated bounding boxes along {axis.toUpperCase()}. Curved surfaces may not touch.</p>
 <button className="workflow-action secondary" disabled={!anchor||!ids.length||busy} onClick={async()=>{const s=useEditor.getState(),source=s.document,selected=[...s.selectedNodeIds];setBusy(true);try{const moving=movableSelection(source,selected),reference=createExportDocument(source,[anchor]);if(moving.some(n=>reference.nodes.some(r=>r.id===n.id)))throw new Error('Choose a reference outside the moving assembly.');if(!Number.isFinite(gap)||Math.abs(gap)>10000)throw new Error('Gap must be within ±10,000 mm.');const [a,b]=await Promise.all([evaluateSnapshot(createExportDocument(source,selected)),evaluateSnapshot(reference)]);if(useEditor.getState().document!==source||JSON.stringify(selected)!==JSON.stringify(useEditor.getState().selectedNodeIds))throw new Error('Model or selection changed. Try alignment again.');const index=['x','y','z'].indexOf(axis),ma=meshBounds(a.positions),mb=meshBounds(b.positions),delta={x:0,y:0,z:0};delta[axis]=side==='after'?mb.max[index]!+gap-ma.min[index]!:mb.min[index]!-gap-ma.max[index]!;s.dispatch({type:'replace-document',document:translateAssembly(source,selected,delta)});setError('');s.setNotice('Assembly aligned with the requested bounding-box gap.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Checking geometry…':'Align selection'}</button>{error&&<p className="workflow-error" role="alert">{error}</p>}
 </section>
}
