import {useEffect,useRef,useState} from 'react'
import {parseModelDocument,type ModelDocument} from '@formforge/model'
import {useEditor} from '@/store/editor'
import {cloudRequest,signInPath,type CloudProject,type CloudComment} from '@/lib/cloud'
import {WorkspaceDialog} from './WorkspaceDialog'
import './CloudWorkspace.css'

export type CloudLink={projectId:string;localId:string;revision:number}
export function CloudWorkspace({onClose,onOpen,link,onLink}:{onClose:()=>void;onOpen:(doc:ModelDocument,project:CloudProject)=>Promise<void>;link:CloudLink|null;onLink:(link:CloudLink|null)=>void}){
 const current=useEditor(s=>s.document),[user,setUser]=useState<{email:string}|null>(null),[ready,setReady]=useState(false),[projects,setProjects]=useState<CloudProject[]>([]),[selected,setSelected]=useState<CloudProject|null>(null),[versions,setVersions]=useState<{revision:number;created:number;bytes:number}[]>([]),[revision,setRevision]=useState(1),[comments,setComments]=useState<CloudComment[]>([]),[comment,setComment]=useState(''),[parent,setParent]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[share,setShare]=useState(''),[deleting,setDeleting]=useState(false)
 const [pendingDeletions,setPendingDeletions]=useState<{id:string;name:string}[]>([])
 const selectionGeneration=useRef(0),alive=useRef(true)
 const refresh=async()=>{const data=await cloudRequest<{projects:CloudProject[];pendingDeletions?:{id:string;name:string}[]}>('/projects');if(alive.current){setProjects(data.projects);setPendingDeletions(data.pendingDeletions??[])}return data.projects}
 const choose=async(p:CloudProject)=>{
  const generation=++selectionGeneration.current;setSelected(p);setRevision(p.revision);setComments([]);setVersions([]);setShare('');setDeleting(false);setParent(null);setComment('')
  const [v,c]=await Promise.all([cloudRequest<{versions:typeof versions}>(`/projects/${p.id}/versions`),cloudRequest<{comments:CloudComment[]}>(`/projects/${p.id}/comments`)])
  if(alive.current&&generation===selectionGeneration.current){setVersions(v.versions);setComments(c.comments)}
 }
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await action()}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Cloud action failed.')}finally{if(alive.current)setBusy(false)}}
 useEffect(()=>{let cancelled=false;alive.current=true;void run(async()=>{
  const session=await cloudRequest<{user:{email:string}|null}>('/session');if(cancelled||!alive.current)return;setUser(session.user);setReady(true)
  if(session.user){const all=await refresh();const token=new URLSearchParams(window.location.hash.split('?')[1]??'').get('review')
   if(token){const joined=await cloudRequest<{project:CloudProject}>('/join',{method:'POST',body:{token}});window.history.replaceState(null,'',window.location.pathname+'#projects');await refresh();await choose(joined.project)}
   else if(link){const p=all.find(p=>p.id===link.projectId);if(p)await choose(p)}
  }
 });return()=>{cancelled=true;alive.current=false;selectionGeneration.current++}},[])
 const selectedComments=comments.filter(c=>c.revision===revision),canUpdate=selected?.role==='owner'&&link?.projectId===selected.id&&link.localId===current.id
 const refreshSelected=async(id:string)=>{const all=await refresh(),p=all.find(p=>p.id===id);if(p)await choose(p);else setSelected(null)}
 return <WorkspaceDialog title="Cloud projects & review" description="Keep a cloud copy, share a review link, and discuss a specific snapshot." onClose={onClose} className="cloud-dialog">
  {busy&&<p role="status">Working…</p>}{error&&<p role="alert" className="workflow-error">{error}</p>}{notice&&<p role="status" className="cloud-notice">{notice}</p>}
  {!ready&&error&&<button className="studio-secondary" onClick={()=>void run(async()=>{const session=await cloudRequest<{user:{email:string}|null}>('/session');setUser(session.user);setReady(true);if(session.user)await refresh()})}>Retry connection</button>}
  {ready&&!user&&<div className="cloud-welcome"><h3>Your workshop, across devices.</h3><p>Sign in to save private cloud projects. Sharing is always an explicit action. Reviewers can open a copy and comment; only you can update your cloud snapshots.</p><a className="studio-primary" href={signInPath()} target="_top">Sign in with ChatGPT</a><p>Modeling and local backups remain available without an account.</p></div>}
  {user&&<><div className="cloud-account"><span>Signed in as {user.email}</span><a href="/signout-with-chatgpt?return_to=%2F%23projects" target="_top">Sign out</a></div>
  <div className="cloud-actions"><button className="studio-primary" disabled={busy} onClick={()=>void run(async()=>{const snapshot=useEditor.getState().document;if(useEditor.getState().placingNodeId)throw new Error('Finish or cancel shape placement before saving to the cloud.');const result=await cloudRequest<{project:CloudProject}>('/projects',{method:'POST',body:{document:snapshot}});onLink({projectId:result.project.id,localId:snapshot.id,revision:result.project.revision});await refresh();await choose(result.project);setNotice('Private cloud copy saved. It includes editable shapes, settings, and any reference image.');})}>Save “{current.name}” as a new cloud project</button><button className="studio-secondary" disabled={busy} onClick={()=>void run(async()=>{if(selected)await refreshSelected(selected.id);else await refresh()})}>Refresh</button></div>
  <p className="cloud-caption">Uploads are manual. Up to 50 projects, 20 snapshots per project, 4 MB per snapshot, and 50 MB total. Keep editable downloads for your own archive.</p>
  {pendingDeletions.map(p=><div className="cloud-notice" key={p.id}><p>Deletion of “{p.name}” is pending. Review access has already been removed.</p><button className="studio-secondary" disabled={busy} onClick={()=>void run(async()=>{await cloudRequest(`/projects/${p.id}`,{method:'DELETE'});await refresh();setNotice('Cloud files deleted.');})}>Retry file deletion</button></div>)}<div className="cloud-layout"><nav className="cloud-projects" aria-label="Cloud projects">{!projects.length&&<p>No cloud projects yet. Save your first copy above.</p>}{projects.map(p=><button key={p.id} className={selected?.id===p.id?'active':''} disabled={busy} onClick={()=>void run(()=>choose(p))}><strong>{p.name}</strong><span>{p.role==='owner'?'Your project':'Shared for review'} · v{p.revision}</span><small>{new Date(p.updated).toLocaleDateString()}</small></button>)}</nav>
  {selected?<section className="cloud-detail"><h3>{selected.name}</h3>{revision<selected.revision&&<p>You are viewing an older snapshot. Open it as a local copy and save a new cloud project to continue without replacing the latest version.</p>}<div className="cloud-actions"><label>Snapshot<select value={revision} disabled={busy||!versions.length} onChange={e=>{setRevision(Number(e.target.value));setParent(null);setComment('')}}>{versions.map(v=><option key={v.revision} value={v.revision}>v{v.revision} · {new Date(v.created).toLocaleString()}</option>)}</select></label><button className="studio-secondary" disabled={busy||!versions.length} onClick={()=>void run(async()=>{const result=await cloudRequest<{document:unknown;project:CloudProject;snapshotRevision:number}>(`/projects/${selected.id}/document?revision=${revision}`);await onOpen(parseModelDocument(result.document),{...result.project,revision:result.snapshotRevision});})}>Open an editable local copy</button></div>
   {selected.role==='owner'&&<><button className="studio-primary" disabled={busy||!canUpdate||selected.revision>=20} onClick={()=>void run(async()=>{const snapshot=useEditor.getState().document;if(snapshot.id!==link?.localId||selected.id!==link?.projectId)throw new Error('Open this cloud project before updating it.');if(useEditor.getState().placingNodeId)throw new Error('Finish placement first.');const result=await cloudRequest<{project:CloudProject}>(`/projects/${selected.id}/document`,{method:'PUT',body:{expectedRevision:link.revision,document:snapshot}});onLink({...link,revision:result.project.revision});await refreshSelected(selected.id);setNotice('New snapshot saved. Earlier snapshots and their reviews are retained.');})}>Save current edits as next snapshot</button>{selected.revision>=20&&<p>This project has 20 retained snapshots. Save a new cloud project to continue its history.</p>}{!canUpdate&&<p>Open an editable copy of this project before updating its cloud snapshots.</p>}
   <details className="cloud-share"><summary>Sharing & ownership</summary><p>Anyone with your link who signs in can read all retained snapshots, download a copy, and comment for seven days. Revoking stops future access; copies already downloaded cannot be recalled. Creating a new link revokes the previous one.</p><div className="cloud-actions"><button className="studio-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await cloudRequest<{url:string}>(`/projects/${selected.id}/share`,{method:'POST',body:{}});setShare(result.url);setSelected({...selected,sharing:true});})}>{selected.sharing?'Replace review link':'Create review link'}</button><button className="studio-secondary" disabled={busy||!selected.sharing} onClick={()=>void run(async()=>{await cloudRequest(`/projects/${selected.id}/share`,{method:'DELETE'});setShare('');setSelected({...selected,sharing:false});setNotice('Review access revoked.');})}>Revoke review access</button></div>{share&&<label>Review link<input readOnly value={share} onFocus={e=>e.target.select()}/><button className="studio-secondary" onClick={()=>void run(async()=>{await navigator.clipboard.writeText(share);setNotice('Review link copied.');})}>Copy link</button></label>}</details></>}
   <section className="cloud-review"><h4>Review · snapshot v{revision}</h4><p>Feedback stays with this snapshot. Open it in the editor to inspect dimensions and print checks.</p>{selectedComments.filter(c=>!c.parent).map(c=><article key={c.id} className={c.resolved?'resolved':''}><header><strong>{c.author}</strong><small>{new Date(c.created).toLocaleString()} · {c.resolved?'Resolved':'Open'}</small></header><p>{c.body}</p>{selectedComments.filter(r=>r.parent===c.id).map(r=><blockquote key={r.id}><strong>{r.author}</strong><p>{r.body}</p></blockquote>)}<div className="cloud-actions"><button className="workflow-text-action" disabled={busy} onClick={()=>{setParent(c.id);document.getElementById('cloud-review-comment')?.focus()}}>Reply</button>{(c.author==='You'||selected.role==='owner')&&<button className="workflow-text-action" disabled={busy} onClick={()=>void run(async()=>{await cloudRequest(`/projects/${selected.id}/comments`,{method:'PATCH',body:{id:c.id,resolved:!c.resolved}});setComments((await cloudRequest<{comments:CloudComment[]}>(`/projects/${selected.id}/comments`)).comments)})}>{c.resolved?'Reopen':'Resolve'}</button>}</div></article>)}{!selectedComments.length&&<p>No feedback on this snapshot yet.</p>}
   <label htmlFor="cloud-review-comment">{parent?'Reply to thread':'New review comment'}<textarea id="cloud-review-comment" value={comment} maxLength={2000} rows={3} onChange={e=>setComment(e.target.value)} disabled={busy}/></label><div className="cloud-actions"><button className="studio-primary" disabled={busy||!comment.trim()} onClick={()=>void run(async()=>{await cloudRequest(`/projects/${selected.id}/comments`,{method:'POST',body:{body:comment,parent,revision}});setComment('');setParent(null);setComments((await cloudRequest<{comments:CloudComment[]}>(`/projects/${selected.id}/comments`)).comments);})}>Post {parent?'reply':'comment'}</button>{parent&&<button className="studio-secondary" onClick={()=>setParent(null)}>Cancel reply</button>}</div></section>
   {selected.role==='owner'&&<details className="cloud-delete"><summary>Delete cloud project</summary><p>Removes all cloud snapshots, comments, and review links. Local copies remain available.</p><label><input type="checkbox" checked={deleting} onChange={e=>setDeleting(e.target.checked)}/> Delete this cloud project and its review history</label><button className="studio-secondary" disabled={busy||!deleting} onClick={()=>void run(async()=>{await cloudRequest(`/projects/${selected.id}`,{method:'DELETE'});if(link?.projectId===selected.id)onLink(null);setSelected(null);await refresh();setNotice('Cloud project deleted.');})}>Delete cloud project</button></details>}
  </section>:<div className="cloud-empty"><h3>A place for feedback.</h3><p>Choose a cloud project to view its snapshots, share it for review, or open an editable copy.</p></div>}</div></>}
 </WorkspaceDialog>
}
