import {useEffect,useState} from 'react'
import {cloudRequest} from '@/lib/cloud'
import './CloudWorkspace.css'
type Progress={completed:string[];analytics:boolean;counts:Record<string,number>}
const empty:Progress={completed:[],analytics:false,counts:{}}
let visitProgress:Progress=empty
const tasks=[
 {id:'first-part',title:'Build a useful first part',steps:['Open CAD tools → Create → Functional recipes. Choose a bracket and review its dimensions.','Create it, select a shape, and adjust its size in Model. Use Undo to compare your change.','Open Print, choose your printer, and review build-plate fit before exporting 3MF.'],tab:'tools',toolkit:'create'},
 {id:'surface-label',title:'Put a label on a face',steps:['Open CAD tools → Create → Workplane and choose Pick a face. Select a flat surface in the solid view.','Open Text. Enter a short label and choose raised or recessed text. Create it on your workplane.','Select the label to change its wording or depth. Inspect the solid result before exporting.'],tab:'tools',toolkit:'create'},
 {id:'fit-and-check',title:'Check a fitted assembly',steps:['Open CAD tools → Prepare → Assembly arrangement. Select a complete part and choose a reference part.','Choose the direction and enter a contact gap. The gap uses evaluated bounds; inspect the actual surfaces.','Open Inspect. Pick a distance or three points for an angle, then pin the result. Print a calibration coupon to test physical fit.'],tab:'tools',toolkit:'prepare'},
 {id:'share-review',title:'Get feedback without losing your version',steps:['Open Cloud & review, sign in, and save a private cloud copy.','Create a seven-day review link. Share it yourself with someone whose feedback you want.','Review comments on their snapshot. Save your changes as a new snapshot, then revoke the link when the review is complete.'],tab:'cloud',toolkit:'create'},
] as const
export function LearningPanel({onLaunch}:{onLaunch:(tab:string,toolkit:string)=>void}){
 const [progress,setProgress]=useState<Progress>(()=>visitProgress),[cloud,setCloud]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState('')
 useEffect(()=>{let cancelled=false;void(async()=>{try{const session=await cloudRequest<{user:unknown}>('/session');if(session.user){const p=await cloudRequest<Progress>('/preferences');if(!cancelled){setProgress(p);setCloud(true)}}else if(!cancelled)setMessage('Sign in through Cloud & review to save your learning progress across devices.')}catch{if(!cancelled)setMessage('Learning progress is available for this visit. Cloud accounts save progress across devices.')}finally{if(!cancelled)setBusy(false)}})();return()=>{cancelled=true}},[])
 const save=async(next:Progress)=>{setBusy(true);try{if(cloud)await cloudRequest('/preferences',{method:'PUT',body:next});if(!cloud)visitProgress=next;setProgress(next);setMessage(cloud?'Learning preferences saved to your account.':'Updated for this visit. Sign in to save progress across devices.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section aria-label="Guided CAD tasks"><h3>Learn by making</h3><p>Four short workflows, with a checklist you control. {progress.completed.length} of 4 completed.</p><div className="learning-list">{tasks.map(task=><article className="learning-task" key={task.id}><h4>{task.title}</h4><ol>{task.steps.map(step=><li key={step}><p>{step}</p></li>)}</ol><label><input type="checkbox" disabled={busy} checked={progress.completed.includes(task.id)} onChange={e=>{const completed=e.target.checked?[...progress.completed,task.id]:progress.completed.filter(id=>id!==task.id);void save({...progress,completed,counts:progress.analytics&&e.target.checked?{...progress.counts,[task.id]:(progress.counts[task.id]??0)+1}:progress.counts})}}/> I completed this workflow</label><br/><button className="studio-secondary" onClick={()=>onLaunch(task.tab,task.toolkit)}>Open the tools for this task</button></article>)}</div>
 <details className="learning-privacy"><summary>Learning privacy & progress</summary><p>Progress records the checklists you mark complete. Optional task statistics count how often you mark each workflow complete. They contain no model content, dimensions, filenames, or review text. Nothing is sent to an external analytics service.</p><label><input type="checkbox" disabled={busy} checked={progress.analytics} onChange={e=>void save({...progress,analytics:e.target.checked,counts:{}})}/> Keep task completion counts {cloud?'in my account':'for this visit'}</label>{progress.analytics&&<ul>{tasks.map(task=><li key={task.id}>{task.title}: {progress.counts[task.id]??0}</li>)}</ul>}<p>Turning statistics off clears the counts. Reset clears both progress and counts.</p><button className="studio-secondary" disabled={busy} onClick={()=>void save(empty)}>Reset learning progress and counts</button></details><p role="status">{message}</p></section>
}
