import {geometryKey} from '@/lib/annotations'
import {useEffect,useState} from 'react'
import {parseModelDocument,type PrinterProfile,type PrintMaterial} from '@formforge/model'
import {useEditor} from '@/store/editor'
import {defaultMaterial,materialEstimate} from '@/lib/materialEstimate'
import {NumberInput} from './NumberInput'
type SavedSetup={name:string;printer:PrinterProfile;material:PrintMaterial}
const storageKey='formforge.print-setups.v1'
export function MaterialProfilesPanel(){
 const doc=useEditor(s=>s.document),mesh=useEditor(s=>s.mesh),meshDoc=useEditor(s=>s.meshDocument),status=useEditor(s=>s.geometryStatus),[draft,setDraft]=useState<PrintMaterial>(doc.printMaterial??defaultMaterial),[saved,setSaved]=useState<SavedSetup[]>([]),[chosen,setChosen]=useState(''),[name,setName]=useState('My print setup'),[error,setError]=useState('')
 useEffect(()=>{setDraft(doc.printMaterial??defaultMaterial)},[doc.id,doc.printMaterial]);useEffect(()=>{try{const items=JSON.parse(localStorage.getItem(storageKey)??'[]');if(Array.isArray(items)&&items.length<=24)setSaved(items.filter((item:SavedSetup)=>{try{if(!item||typeof item.name!=='string'||!item.name.trim()||item.name.length>80)return false;parseModelDocument({...useEditor.getState().document,printer:item.printer,printMaterial:item.material});return !!item.printer&&!!item.material}catch{return false}}))}catch{}},[])
 let estimate:ReturnType<typeof materialEstimate>|null=null;try{if(mesh&&meshDoc===doc&&status==='ready')estimate=materialEstimate(mesh.volume,{...(doc.printMaterial??defaultMaterial),slicerGrams:doc.printMaterial?.slicerGeometryKey===geometryKey(doc)?doc.printMaterial.slicerGrams:undefined})}catch{}
 const apply=(material:PrintMaterial,printer=useEditor.getState().document.printer)=>{const s=useEditor.getState();const next=parseModelDocument({...s.document,printer,printMaterial:{...material,slicerGeometryKey:geometryKey(s.document)},revision:s.document.revision+1,updatedAt:new Date().toISOString()});s.dispatch({type:'replace-document',document:next});setError('')}
 return <section className="workflow-card"><h3>Material and cost</h3><label className="cad-select-label">Material name<input maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="size-fields"><NumberInput label="Density g/cm³" value={draft.density} onChange={v=>setDraft({...draft,density:v})}/><NumberInput label="Price per kg" value={draft.pricePerKg} onChange={v=>setDraft({...draft,pricePerKg:v})}/></div><label className="cad-select-label">Currency<select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}>{['USD','EUR','GBP','CAD','AUD','INR'].map(c=><option key={c}>{c}</option>)}</select></label><p>Density 1.24 is a starting assumption. Enter your material supplier's value and the price you paid.</p><details><summary>Slicer-reported results</summary><NumberInput label="Slicer mass (g, 0 if unknown)" value={draft.slicerGrams??0} onChange={v=>setDraft({...draft,slicerGrams:v})}/><NumberInput label="Slicer duration (minutes)" value={draft.slicerMinutes??0} onChange={v=>setDraft({...draft,slicerMinutes:v})}/></details><button className="workflow-action" onClick={()=>{try{apply(draft)}catch(e){setError((e as Error).message)}}}>Apply material</button>
 {estimate?<><dl className="print-summary"><div><dt>Solid-material equivalent</dt><dd>{estimate.solidGrams.toFixed(2)} g</dd></div><div><dt>Solid material cost</dt><dd>{(doc.printMaterial??defaultMaterial).currency} {estimate.solidCost.toFixed(2)}</dd></div>{estimate.slicerCost!==null&&<div><dt>Cost from entered slicer mass</dt><dd>{doc.printMaterial?.currency} {estimate.slicerCost.toFixed(2)}</dd></div>}</dl><p>This is the mass/cost of fully solid geometry. Infill, shells, supports, waste, energy, and print time require slicing. No G-code is generated here.</p></>:<p>Estimates appear after the current solid finishes building.</p>}
 {doc.printMaterial?.slicerGrams!==undefined&&doc.printMaterial.slicerGeometryKey!==geometryKey(doc)&&<p>Slicer results need review because the geometry changed. Enter fresh results before applying material.</p>}<h4>Saved printer + material setups</h4><label className="cad-select-label">Setup name<input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="workflow-action secondary" onClick={()=>{try{if(!name.trim())throw new Error('Name this setup.');parseModelDocument({...doc,printMaterial:draft});const next=[...saved.filter(p=>p.name!==name.trim()),{name:name.trim(),printer:doc.printer,material:{...draft,slicerGrams:undefined,slicerMinutes:undefined,slicerGeometryKey:undefined}}];if(next.length>24)throw new Error('Keep up to 24 setups.');localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);setError('')}catch(e){setError((e as Error).message)}}}>Save setup on this device</button><label className="cad-select-label">Saved setup<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose setup</option>{saved.map(s=><option key={s.name}>{s.name}</option>)}</select></label><div className="workflow-actions"><button className="workflow-action secondary" disabled={!chosen} onClick={()=>{try{const selected=saved.find(s=>s.name===chosen);if(selected)apply(selected.material,selected.printer)}catch(e){setError((e as Error).message)}}}>Load setup</button><button className="workflow-text-action" disabled={!chosen} onClick={()=>{try{const next=saved.filter(s=>s.name!==chosen);localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);setChosen('')}catch{setError('Could not update local setup storage.')}}}>Remove setup</button></div>{error&&<p role="alert" className="workflow-error">{error}</p>}</section>
}
