import {useState} from 'react'
import {parseModelDocument} from '@formforge/model'
import {useEditor} from '@/store/editor'
import {geometryKey} from '@/lib/annotations'
import {printProtocols} from '@/lib/printProtocols'
import {downloadBlob,safeFilename} from '@/lib/download'
export function PrintEvidencePanel(){
 const doc=useEditor(s=>s.document),[protocol,setProtocol]=useState<string>(printProtocols[0].id),[printer,setPrinter]=useState(doc.printer.name),[material,setMaterial]=useState(doc.printMaterial?.name??''),[layer,setLayer]=useState('.2'),[expected,setExpected]=useState(''),[measured,setMeasured]=useState(''),[tolerance,setTolerance]=useState('.2'),[notes,setNotes]=useState(''),[photo,setPhoto]=useState<string|undefined>(),[confirmedKey,setConfirmedKey]=useState<string|null>(null),[error,setError]=useState('')
 const chosen=printProtocols.find(p=>p.id===protocol)!,key=geometryKey(doc),records=doc.printTests??[]
 const confirmationKey=JSON.stringify([doc.id,key,doc.printer,protocol,printer,material,layer,expected,measured,tolerance,notes,photo]),confirmed=confirmedKey===confirmationKey
 const setConfirmed=(value:boolean)=>setConfirmedKey(value?confirmationKey:null)
 const field=(label:string,v:string,set:(v:string)=>void)=><label className="cad-select-label">{label}<input type="number" step=".01" min="0" value={v} onChange={e=>set(e.target.value)} required/></label>
 return <details className="workflow-card"><summary>Physical print record · {records.length} self-reported tests</summary><p>Record an actual print and measured result. Records stay in this project; they do not mark public templates as verified.</p><form onSubmit={e=>{e.preventDefault();try{if(!confirmed)throw new Error('Confirm this part was physically printed and measured.');const current=useEditor.getState().document;if(current.id!==doc.id||geometryKey(current)!==key)throw new Error('Geometry changed. Review the measured version before recording.');const date=new Date(),test={id:crypto.randomUUID(),protocol,date:`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,printer,material,nozzle:doc.printer.nozzleDiameter,layerHeight:Number(layer),expected:Number(expected),measured:Number(measured),tolerance:Number(tolerance),geometryKey:key,notes,photoDataUrl:photo};const next=parseModelDocument({...current,printTests:[...(current.printTests??[]),test],revision:current.revision+1,updatedAt:new Date().toISOString()});useEditor.getState().dispatch({type:'replace-document',document:{...current,printTests:next.printTests,revision:next.revision,updatedAt:next.updatedAt}});setConfirmed(false);setError('')}catch(cause){setError((cause as Error).message)}}}>
  <label className="cad-select-label">Test protocol<select value={protocol} onChange={e=>setProtocol(e.target.value)}>{printProtocols.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><p>{chosen.steps}</p><label className="cad-select-label">Printer used<input required maxLength={120} value={printer} onChange={e=>setPrinter(e.target.value)}/></label><label className="cad-select-label">Material used<input required maxLength={80} value={material} onChange={e=>setMaterial(e.target.value)}/></label>{field('Layer height (mm)',layer,setLayer)}<p>Configured nozzle: {doc.printer.nozzleDiameter} mm. Update Printer setup if different.</p><div className="template-dimension-grid">{field(`Expected ${chosen.measure.toLowerCase()} (mm)`,expected,setExpected)}{field('Measured value (mm)',measured,setMeasured)}{field('Allowed deviation ± mm',tolerance,setTolerance)}</div><label className="cad-select-label">Conditions and observations<textarea value={notes} maxLength={1000} rows={3} onChange={e=>setNotes(e.target.value)}/></label><label className="cad-select-label">Optional photo · PNG, JPEG or WebP, up to 600 KB<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>590_000||!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose PNG, JPEG or WebP below 600 KB.');return}const reader=new FileReader();reader.onload=()=>{setPhoto(String(reader.result));setError('')};reader.onerror=()=>setError('Could not read that photo.');reader.readAsDataURL(file)}}/></label>{photo&&<><img src={photo} alt="Photo attached to this print record" style={{maxWidth:'100%',maxHeight:160}}/><button type="button" onClick={()=>setPhoto(undefined)}>Remove draft photo</button></>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I physically printed and measured this geometry with the settings above.</label><button type="submit" className="workflow-action" disabled={!confirmed||records.length>=20}>Record physical test</button>{error&&<p className="workflow-error" role="alert">{error}</p>}
 </form>{records.map(r=><article key={r.id} className="slicer-handoff"><strong>{printProtocols.find(p=>p.id===r.protocol)?.name??r.protocol}</strong><p>{r.date} · {r.printer} · {r.material}</p><p>{r.measured} mm measured / {r.expected} mm expected · ±{r.tolerance} mm allowed</p><strong>{Math.abs(r.measured-r.expected)<=r.tolerance?'Measurement within entered tolerance':'Measurement outside entered tolerance'}</strong><p>{r.geometryKey===key?'Matches current geometry':'Historical geometry · current model has changed'} · self-reported</p><p>{r.notes}</p>{r.photoDataUrl&&<img src={r.photoDataUrl} alt="User-supplied photo of the measured print" style={{maxWidth:'100%',maxHeight:180}}/>}</article>)}{!!records.length&&<button className="workflow-action secondary" onClick={()=>downloadBlob(new Blob([JSON.stringify({project:doc.name,records},null,2)],{type:'application/json'}),`${safeFilename(doc.name)}-print-evidence.json`)}>Download print records and photos</button>}</details>
}
