import {lazy,Suspense,useState} from 'react'
import {ArrowRight,Box,Check,Play,Search} from 'lucide-react'
import {findTemplates,templateCatalog} from '@/lib/templateCatalog'
const PublicDemo=lazy(()=>import('./PublicDemo').then(m=>({default:m.PublicDemo})))
export function PublicWebsite({templatesOnly=false}:{templatesOnly?:boolean}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[demo,setDemo]=useState(false)
 const templates=findTemplates(query,category),LibraryHeading=templatesOnly?'h1':'h2'
 return <div className="public-site"><a className="skip-link" href="#public-main" onClick={e=>{e.preventDefault();document.getElementById('public-main')?.focus()}}>Skip to content</a>
  <header className="public-header"><a className="public-brand" href="#home"><span className="brand-mark"><span/></span>FormForge</a><nav aria-label="Main navigation"><a href="#templates" aria-current={templatesOnly?'page':undefined}>Templates</a><a href="#projects">My workshop</a><a className="public-primary" href="#studio">Open studio <ArrowRight size={16}/></a></nav></header>
  <main id="public-main" tabIndex={-1}>
   {!templatesOnly&&<section className="public-hero"><div><span className="public-eyebrow">BROWSER CAD FOR EVERYDAY MAKERS</span><h1>From “I need a part”<br/>to your next print.</h1><p>Start with an editable design. Make it your size, check it on the build plate, and take it to your slicer.</p><div className="public-actions"><a className="public-primary" href="#templates">Find a useful template <ArrowRight size={18}/></a><button className="public-secondary" onClick={()=>setDemo(true)}><Play size={16}/> Try the interactive demo</button></div><ul className="public-benefits"><li><Check size={16}/> No installation</li><li><Check size={16}/> Start without an account</li><li><Check size={16}/> Editable project backups</li></ul></div><figure className="public-hero-model"><span className="model-tag">EDITABLE EXAMPLE · ENCLOSURE</span><img src="/templates/enclosure.svg" alt="Evaluated enclosure geometry with a separate lid" width="600" height="400"/><figcaption><span>80 × 50 × 25 mm body</span><a href="#studio?starter=enclosure">Make it yours <ArrowRight size={16}/></a></figcaption></figure></section>}
   <section className="public-library" aria-labelledby="template-heading"><div className="public-section-heading"><div><span className="public-eyebrow">START WITH SOMETHING USEFUL</span><LibraryHeading id="template-heading">{templatesOnly?'Editable templates':'A small part. A useful starting point.'}</LibraryHeading><p>Real geometry you can change. All dimensions are examples; physical print testing is pending.</p></div>{!templatesOnly&&<a href="#templates">Browse all templates <ArrowRight size={16}/></a>}</div>
    <div className="public-filters"><label className="public-search"><Search size={18}/><span className="sr-only">Search templates</span><input type="search" placeholder="Try spacer, cable, enclosure…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(templateCatalog.map(t=>t.category))].map(c=><option key={c}>{c}</option>)}</select></label></div>
    <p className="public-results" role="status">{templates.length} editable templates</p>
    {!templates.length&&<div className="public-empty"><p>No templates match that search.</p><button className="public-secondary" onClick={()=>{setQuery('');setCategory('All')}}>Show all templates</button></div>}
    <div className="public-template-grid">{templates.map(item=><article key={item.id} className="public-template"><a className="template-image" href={`/templates/${item.id}`} aria-label={`Preview ${item.name}`}><img src={`/templates/${item.id}.svg`} loading="lazy" alt={`${item.name} evaluated geometry`} width="600" height="400"/></a><div className="template-copy"><div className="template-meta"><span>{item.category}</span><span>{item.level}</span></div><h3>{item.name}</h3><p>{item.description}</p><strong className="template-dimensions">{item.dimensions}</strong><details><summary>Editing & print notes</summary><ol>{item.steps.map(step=><li key={step}>{step}</li>)}</ol><p>{item.printNote}</p><small>Physical print evidence: pending. Render shows the digital design.</small></details><a className="template-open" href={`/templates/${item.id}`}>View template & customize <ArrowRight size={16}/></a></div></article>)}</div>
   </section>
   <section className="public-workflow"><div><span className="public-eyebrow">YOUR DESIGN STAYS EDITABLE</span><h2>Choose. Adjust. Inspect. Print.</h2><p>Keep the shapes and dimensions behind your model, so the next change is easier.</p></div><ol><li><span>01</span><strong>Start with a part</strong><p>Use a template, bring your mesh, or build from shapes.</p></li><li><span>02</span><strong>Make it fit</strong><p>Edit dimensions, compare clearances and record a tested fit.</p></li><li><span>03</span><strong>Check the handoff</strong><p>Review size, placement and potential overhangs before export.</p></li></ol></section>
   <section className="public-storage"><Box size={26}/><div><h2>Know where your work is saved.</h2><p>Projects and recovery copies stay in this browser. Download an editable backup for a separate copy, or sign in to save an explicit cloud snapshot. STL and 3MF exports go to your slicer for supports and printer settings.</p></div><a className="public-secondary" href="#projects">Open my workshop</a></section>
  </main><footer className="public-footer"><strong>FormForge</strong><span>Useful parts, built one change at a time.</span><a href="#studio">Start designing</a></footer>
  {demo&&<Suspense fallback={<div className="public-demo-loading" role="status">Loading the interactive demo… <button onClick={()=>setDemo(false)}>Cancel</button></div>}><PublicDemo onClose={()=>setDemo(false)}/></Suspense>}
 </div>
}
