import {useState} from 'react'
import type {ReferenceImage} from '@formforge/model'
import {useEditor} from '@/store/editor'
import {axisWorkplane} from '@/lib/workplanes'
import {calibratedScale,loadReferenceImage} from '@/lib/referenceImages'
import {NumberInput} from './NumberInput'
export function ReferenceImagePanel(){
 const doc=useEditor(s=>s.document),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mm,setMm]=useState(25.4),[points,setPoints]=useState([{x:0,y:0},{x:100,y:0}]),[pick,setPick]=useState(0)
 const image=doc.referenceImages?.[0]
 const update=(patch:Partial<ReferenceImage>)=>{const s=useEditor.getState();if(!s.document.referenceImages?.[0])return;s.dispatch({type:'replace-document',document:{...s.document,referenceImages:[{...s.document.referenceImages[0],...patch}],revision:s.document.revision+1,updatedAt:new Date().toISOString()}})}
 return <section className="workflow-card"><h3>Image reference</h3><p>Trace a local image on the active workplane. Images are saved in editable backups and excluded from manufacturing files.</p>
 <label className="cad-select-label">Choose image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const source=useEditor.getState().document;setBusy(true);try{const next=await loadReferenceImage(file,source.workplane??axisWorkplane('xy'));if(useEditor.getState().document!==source)throw new Error('Project changed while loading. Choose the image again.');useEditor.getState().dispatch({type:'replace-document',document:{...source,referenceImages:[next],revision:source.revision+1,updatedAt:new Date().toISOString()}});setPoints([{x:0,y:0},{x:next.width,y:0}]);setError('')}catch(c){setError(c instanceof Error?c.message:'Could not decode this image.')}finally{setBusy(false);e.target.value=''}}}/></label>
 {image&&<><p>{image.name} · {(image.width*image.mmPerPixel).toFixed(2)} × {(image.height*image.mmPerPixel).toFixed(2)} mm</p><p>Click two known points, or enter their image coordinates below.</p><button className="reference-preview" aria-label={`Pick calibration point ${pick+1}`} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();const p={x:(e.clientX-r.left)/r.width*image.width,y:(e.clientY-r.top)/r.height*image.height};setPoints(old=>old.map((v,i)=>i===pick?p:v));setPick(1-pick)}}><img alt={`Calibration reference: ${image.name}`} src={image.dataUrl}/>{points.map((p,i)=><span key={i} style={{left:`${p.x/image.width*100}%`,top:`${p.y/image.height*100}%`}}>{i+1}</span>)}</button>
 {points.map((p,i)=><div className="size-fields" key={i}>{(['x','y'] as const).map(axis=><NumberInput key={axis} label={`Point ${i+1} ${axis.toUpperCase()} px`} value={p[axis]} onChange={v=>setPoints(old=>old.map((q,j)=>i===j?{...q,[axis]:v}:q))}/>)}</div>)}
 <NumberInput label="Known distance" suffix="mm" value={mm} onChange={setMm}/><button className="workflow-action" onClick={()=>{try{if(points.some(p=>p.x<0||p.y<0||p.x>image.width||p.y>image.height))throw new Error('Calibration points must be inside the image.');update({mmPerPixel:calibratedScale(points[0]!,points[1]!,mm)});setError('')}catch(e){setError((e as Error).message)}}}>Calibrate image</button>
 <label className="cad-select-label">Opacity<input type="range" min="0.1" max="1" step="0.1" value={image.opacity} onChange={e=>update({opacity:Number(e.target.value)})}/></label>
 <div className="workflow-actions"><button className="workflow-action secondary" onClick={()=>update({visible:!image.visible})}>{image.visible?'Hide image':'Show image'}</button><button className="workflow-action secondary" onClick={()=>update({plane:structuredClone(useEditor.getState().document.workplane??axisWorkplane('xy'))})}>Use active plane</button><button className="workflow-text-action" onClick={()=>{const s=useEditor.getState();s.dispatch({type:'replace-document',document:{...s.document,referenceImages:[],revision:s.document.revision+1,updatedAt:new Date().toISOString()}})}}>Remove image</button></div></>}
 {busy&&<p role="status">Preparing image…</p>}{error&&<p role="alert" className="workflow-error">{error}</p>}
 </section>
}
