import { useState } from 'react'
import { parseModelDocument, type SavedCameraView } from '@formforge/model'
import { useEditor } from '@/store/editor'
import { WorkspaceDialog } from './WorkspaceDialog'
export function SavedViewsDialog({onClose}:{onClose:()=>void}){
 const doc=useEditor(s=>s.document),[name,setName]=useState('Detail view'),[error,setError]=useState('')
 const update=(views:SavedCameraView[])=>{const s=useEditor.getState();parseModelDocument({...s.document,savedViews:views});s.dispatch({type:'replace-document',document:{...s.document,savedViews:views,revision:s.document.revision+1,updatedAt:new Date().toISOString()}})}
 return <WorkspaceDialog title="Saved camera views" description="Keep up to 12 views in this project and its editable backup." onClose={onClose}><label className="cad-select-label">View name<input maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><button className="workflow-action" disabled={!name.trim()||(doc.savedViews?.length??0)>=12} onClick={()=>{try{let captured=false;window.dispatchEvent(new CustomEvent('formforge:capture-camera',{detail:{receive:(pose:Omit<SavedCameraView,'id'|'name'>)=>{update([...(doc.savedViews??[]),{...pose,id:crypto.randomUUID(),name:name.trim()}]);captured=true}}}));if(!captured)throw new Error('The canvas is not ready. Try again.');setError('')}catch(e){setError((e as Error).message)}}}>Save current view</button><div className="saved-views">{doc.savedViews?.map(view=><div key={view.id}><input aria-label={`Rename view ${view.name}`} maxLength={60} defaultValue={view.name} onBlur={e=>{const name=e.target.value.trim()||view.name;if(name===view.name)return;try{update(doc.savedViews!.map(v=>v.id===view.id?{...v,name}:v));setError('')}catch(error){setError((error as Error).message)}}}/><button onClick={()=>{window.dispatchEvent(new CustomEvent('formforge:restore-camera',{detail:view}));onClose()}}>{view.name}</button><button aria-label={`Delete view ${view.name}`} onClick={()=>{try{update(doc.savedViews!.filter(v=>v.id!==view.id))}catch(e){setError((e as Error).message)}}}>Remove</button></div>)}</div>{!doc.savedViews?.length&&<p>No saved views yet. Orbit to a useful angle and save it.</p>}{error&&<p role="alert">{error}</p>}</WorkspaceDialog>
}
