import {useState} from 'react'
import {parseModelDocument,type SavedCameraView} from '@formforge/model'
import {useEditor} from '@/store/editor'
import {captureInspection,restoreInspection} from '@/lib/inspectionBookmarks'
import {WorkspaceDialog} from './WorkspaceDialog'
import './PrecisionWorkflows.css'
export function SavedViewsDialog({onClose}:{onClose:()=>void}){
 const doc=useEditor(s=>s.document),[name,setName]=useState('Detail view'),[include,setInclude]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState('')
 const update=(views:SavedCameraView[])=>{const s=useEditor.getState();parseModelDocument({...s.document,savedViews:views});s.dispatch({type:'replace-document',document:{...s.document,savedViews:views,revision:s.document.revision+1,updatedAt:new Date().toISOString()}})}
 const capture=(id?:string)=>{try{let captured=false;window.dispatchEvent(new CustomEvent('formforge:capture-camera',{detail:{receive:(pose:Omit<SavedCameraView,'id'|'name'>)=>{const current=useEditor.getState().document,old=current.savedViews?.find(v=>v.id===id),view={...pose,id:id??crypto.randomUUID(),name:old?.name??name.trim(),...(include?{inspection:captureInspection()}:{})};update(id?current.savedViews!.map(v=>v.id===id?view:v):[...current.savedViews??[],view]);captured=true}}}));if(!captured)throw new Error('The canvas is not ready. Try again.');setError('');setStatus('View saved in this project. Undo restores the previous views.')}catch(e){setError((e as Error).message)}}
 return <WorkspaceDialog portal title="Saved camera views" description="Save an angle and projection, with optional section, display and isolation settings. Up to 12 views per project." onClose={onClose} className="precision-dialog">
 <label className="cad-select-label">View name<input maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label>
 <label className="precision-check"><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)}/>Include section, display, and isolated shapes</label>
 <button className="studio-primary" disabled={!name.trim()||(doc.savedViews?.length??0)>=12} onClick={()=>capture()}>Save current view</button>
 <div className="precision-list">{doc.savedViews?.map(view=><article key={view.id}><div className="precision-row"><input aria-label={`Rename view ${view.name}`} maxLength={60} defaultValue={view.name} key={view.name} onBlur={e=>{const name=e.target.value.trim()||view.name;if(name===view.name)return;try{update(doc.savedViews!.map(v=>v.id===view.id?{...v,name}:v));setError('')}catch(error){setError((error as Error).message)}}}/><button onClick={()=>{if(view.inspection)restoreInspection(view.inspection);window.dispatchEvent(new CustomEvent('formforge:restore-camera',{detail:view}));onClose()}}>{view.name}</button></div><p>{view.projection==='orthographic'?'Orthographic':'Perspective'} · {view.inspection?`${view.inspection.section.enabled?'Section on':'Full model'} · ${view.inspection.displayMode}${view.inspection.focusIds.length?` · ${view.inspection.focusIds.length} isolated shapes`:''}`:'Camera only'}</p><div className="precision-row"><button onClick={()=>capture(view.id)}>Update from current view</button><button aria-label={`Delete view ${view.name}`} onClick={()=>{try{update(doc.savedViews!.filter(v=>v.id!==view.id))}catch(e){setError((e as Error).message)}}}>Remove</button></div></article>)}</div>
 {!doc.savedViews?.length&&<p>No saved views yet. Orbit to a useful angle and save it.</p>}{error&&<p role="alert" className="workflow-error">{error}</p>}{status&&<p role="status">{status}</p>}
 </WorkspaceDialog>
}
