import { useEffect, useMemo, useState } from 'react'
import type { MeshPayload, ModelDocument } from '@formforge/model'
import { createStarter, starters } from '@/lib/starters'
import { evaluateSnapshot } from '@/geometry/evaluateSnapshot'
import { MeshPreview } from './MeshPreview'
import { WorkspaceDialog } from './WorkspaceDialog'
export function StarterDialog({onClose,onCreate}:{onClose:()=>void;onCreate:(doc:ModelDocument)=>Promise<void>}){
 const [query,setQuery]=useState('')
 const [id,setId]=useState(starters[0]!.id),[mesh,setMesh]=useState<MeshPayload|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),doc=useMemo(()=>createStarter(id),[id]);const item=starters.find(s=>s.id===id)!
 useEffect(()=>{const controller=new AbortController();setMesh(null);setError('');void evaluateSnapshot(doc,controller.signal).then(result=>{if(!controller.signal.aborted)setMesh(result)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[doc])
 return <WorkspaceDialog title="Start with a useful part" description="Real editable geometry. Make a copy, adjust it, then check it in your slicer." onClose={onClose} className="export-dialog"><label className="cad-select-label">Find a starter<input type="search" value={query} placeholder="Enclosure, bracket, fit…" onChange={e=>setQuery(e.target.value)}/></label><div className="starter-grid">{starters.filter(s=>`${s.name} ${s.description}`.toLowerCase().includes(query.toLowerCase().trim())).map(s=><button key={s.id} aria-pressed={id===s.id} disabled={busy} onClick={()=>setId(s.id)}><strong>{s.name}</strong><span>{s.description}</span></button>)}</div>{!starters.some(s=>`${s.name} ${s.description}`.toLowerCase().includes(query.toLowerCase().trim()))&&<p role="status">No starters match. Clear the search to see all four parts.</p>}{mesh?<MeshPreview mesh={mesh} label={item.name+' evaluated geometry'}/>:<p role="status">{error||'Building starter preview…'}</p>}<p>{item.learn}</p><p className="workflow-caption">Starter dimensions are examples. Fit, flex and strength need testing with your printer and material.</p><footer className="dialog-footer"><span>Saved as your own project on this device.</span><button className="studio-primary" disabled={!mesh||busy} onClick={async()=>{setBusy(true);try{await onCreate(doc)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Use this starter</button></footer></WorkspaceDialog>
}
