import {useEffect,useState} from 'react'
import type {ModelNode} from '@formforge/model'
import {useEditor} from '@/store/editor'
import {createTextNode,updatedTextTransform} from '@/lib/textGeometry'
import {placeNodeOnWorkplane} from '@/lib/workplanes'
import {NumberInput} from './NumberInput'
export function TextPanel({node}:{node?:ModelNode}) {
 const [content,setContent]=useState(node?.text?.content??'FORMFORGE'),[size,setSize]=useState(node?.text?.size??10),[depth,setDepth]=useState(node?.text?.depth??2),[mode,setMode]=useState<'add'|'cut'>(node?.boolean==='cut'?'cut':'add'),[error,setError]=useState('')
 useEffect(()=>{if(node?.text){setContent(node.text.content);setSize(node.text.size);setDepth(node.text.depth);setMode(node.boolean==='cut'?'cut':'add')}},[node])
 return <section className="workflow-card"><h3>{node?'Edit text':'Emboss / deboss text'}</h3><label className="cad-select-label">Text<textarea aria-label="Label text" maxLength={80} rows={2} value={content} onChange={e=>setContent(e.target.value)}/></label><div className="size-fields"><NumberInput label="Text size" suffix="mm" value={size} onChange={setSize}/><NumberInput label="Text depth" suffix="mm" value={depth} onChange={setDepth}/></div><label className="cad-select-label">Operation<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="add">Raised text (solid)</option><option value="cut">Recessed text (cutout)</option></select></label><p>Helvetiker · centered label. Raised text starts on the active workplane; recessed text extends into it. Position it to overlap your part.</p>{error&&<p role="alert" className="workflow-error">{error}</p>}<button className="workflow-action" disabled={node?.locked} onClick={()=>{try {const s=useEditor.getState();if(s.document.sculptStrokes.length)throw new Error('Convert volume sculpting to a mesh before adding or changing text.');const text=createTextNode({content,size,depth,font:'helvetiker'},mode);if(node){s.updateNode(node.id,{mesh:text.mesh,text:text.text,name:text.name,boolean:mode,transform:updatedTextTransform(node,depth,mode)})}else{const placed=placeNodeOnWorkplane(text,s.document.workplane,{x:0,y:0});if(mode==='cut'){const n=s.document.workplane?.normal??{x:0,y:0,z:1};placed.transform.position.x-=n.x*depth;placed.transform.position.y-=n.y*depth;placed.transform.position.z-=n.z*depth}s.dispatch({type:'add-node',node:placed});s.selectNode(placed.id)}setError('');s.setNotice('Editable text saved. Select the label to revise its wording.')}catch(e){setError(e instanceof Error?e.message:'Could not create text.')}}}>{node?'Update text':'Create text'}</button></section>
}
