import {describe,it,expect} from 'vitest'
import {createDocument,createNode,vec3} from '@formforge/model'
import {transformAssembly} from './precisionTransform'
import {createAttachedHole} from './attachedHoles'

const draft={translation:vec3(),rotation:vec3(),scale:1,pivot:'world' as const}
describe('precision assembly transforms',()=>{
 it('moves a complete cutter group and preserves unrelated shapes',()=>{const a=createNode('box'),b=createNode('cylinder','cut'),c=createNode('sphere');a.combined=b.combined=true;a.groupId=b.groupId='g';const doc={...createDocument(),nodes:[a,b,c]};const next=transformAssembly(doc,[a.id],a.id,{...draft,translation:vec3(3,4,5)});expect(next.nodes.slice(0,2).map(n=>n.transform.position)).toEqual([vec3(3,4,5),vec3(3,4,5)]);expect(next.nodes[2]).toBe(c);expect(doc.nodes[0]!.transform.position).toEqual(vec3())})
 it('rotates around the active origin and uniformly scales offsets',()=>{const a=createNode('box','add',vec3(10,0,0)),b=createNode('box','add',vec3(20,0,0));const next=transformAssembly({...createDocument(),nodes:[a,b]},[a.id,b.id],a.id,{...draft,pivot:'active',rotation:vec3(0,0,90),scale:2});expect(next.nodes[0]!.transform.position.x).toBeCloseTo(10);expect(next.nodes[1]!.transform.position.y).toBeCloseTo(20);expect(next.nodes[1]!.transform.scale).toEqual(vec3(2,2,2))})
 it('keeps the source bounds center fixed during uniform scaling',()=>{const a=createNode('box','add',vec3(-10,0,5)),b=createNode('box','add',vec3(10,0,5));const next=transformAssembly({...createDocument(),nodes:[a,b]},[a.id,b.id],a.id,{...draft,pivot:'center',scale:2});expect(next.nodes.map(n=>n.transform.position)).toEqual([vec3(-20,0,5),vec3(20,0,5)])})
 it('detaches only changed transform bindings, preserving size formulas',()=>{const a=createNode('box');a.parameterBindings={positionX:'Width',positionY:'0',width:'Width'};const next=transformAssembly({...createDocument(),nodes:[a]},[a.id],a.id,{...draft,translation:vec3(2,0,0)});expect(next.nodes[0]!.parameterBindings).toEqual({positionY:'0',width:'Width'})})
 it('rejects locked assembly members, volume strokes and invalid scale',()=>{const a=createNode('box'),b=createNode('box');a.assemblyPath=b.assemblyPath=['a'];b.locked=true;const doc={...createDocument(),nodes:[a,b]};expect(()=>transformAssembly(doc,[a.id],a.id,{...draft,translation:vec3(1,0,0)})).toThrow(/Unlock/);b.locked=false;expect(()=>transformAssembly(doc,[a.id],a.id,{...draft,scale:0})).toThrow(/scale/i);expect(()=>transformAssembly(doc,[a.id],a.id,{...draft,translation:vec3(Infinity,0,0)})).toThrow(/finite|10,000/);expect(()=>transformAssembly({...doc,sculptStrokes:[{} as never]},[a.id],a.id,draft)).toThrow(/sculpt/i)})
 it('preserves attached holes under rigid moves and refuses unsupported scaling',()=>{const a=createNode('box'),hole=createAttachedHole(a,'z+',4,0,0,'through',1),doc={...createDocument(),nodes:[a,hole]};const next=transformAssembly(doc,[hole.id],a.id,{...draft,translation:vec3(7,0,0)});expect(next.nodes.every(n=>Math.abs(n.transform.position.x-7)<1e-6)).toBe(true);expect(()=>transformAssembly(doc,[a.id],a.id,{...draft,scale:2})).toThrow(/attached/i)})
 it('returns the identical document for a no-op',()=>{const a=createNode('box'),doc={...createDocument(),nodes:[a]};expect(transformAssembly(doc,[a.id],a.id,draft)).toBe(doc)})
})
