export type StarterId='enclosure'|'bracket'|'adapter'|'snapfit'|'coupon'|'washer'|'tray'|'cable-guide'
export interface TemplateInfo{id:StarterId;name:string;description:string;learn:string;category:string;level:string;dimensions:string;tags:string;steps:string[];printNote:string}
export const templateCatalog:TemplateInfo[]=[
 {id:'enclosure',name:'Electronics enclosure',description:'A hollow case with mounting bosses and a separate lid.',learn:'Adjust shell dimensions, pilot holes and lid clearance.',category:'Enclosures',level:'Intermediate',dimensions:'80 × 50 × 25 mm body',tags:'case box electronics lid',steps:['Choose the shell and cavity to change the case size.','Adjust mounting bosses and pilot holes to suit your board.','Check lid clearance with your printer, then arrange the two parts for export.'],printNote:'Print the body open-side up. Test lid fit before a full-size print.'},
 {id:'bracket',name:'Mounting bracket',description:'An L bracket with holes through its foot and upright.',learn:'Explore grouped solids and subtractive holes.',category:'Hardware',level:'Beginner',dimensions:'80 × 50 × 25 mm',tags:'mount angle fixing support',steps:['Adjust the foot and upright dimensions.','Move the mounting-hole shapes to match your fixings.','Review orientation and loads before printing.'],printNote:'Example geometry only; strength and fastening loads have not been tested.'},
 {id:'adapter',name:'Hollow adapter',description:'A tapered, open transition between two round openings.',learn:'Adjust the taper and the two nested shapes.',category:'Hardware',level:'Intermediate',dimensions:'80 → 50 mm diameter · 25 mm high',tags:'tube reducer duct funnel transition',steps:['Set the outer opening radii and height.','Update the inner shape to preserve the intended wall.','Print a short fit sample before making the full adapter.'],printNote:'Clearance depends on the mating part. Not pressure-rated.'},
 {id:'snapfit',name:'Snap-fit test pair',description:'A cantilever and matching catch for fit experiments.',learn:'Compare flexibility and clearance on your printer.',category:'Calibration',level:'Intermediate',dimensions:'48 mm beam · 0.2 mm starting clearance',tags:'snap clip flex fit test',steps:['Print the example pair with the same material and settings as your part.','Check flex, engagement and clearance.','Adjust the slot and hook in small increments.'],printNote:'Repeated flex and retention are untested. Do not assume one clearance suits every material.'},
 {id:'coupon',name:'Hole & pin fit coupon',description:'Five hole sizes and a separate pin gauge.',learn:'Find a clearance that works for your printer and material.',category:'Calibration',level:'Beginner',dimensions:'4 mm pin · +0.1 to +0.5 mm diametral clearance',tags:'tolerance gauge hole printer calibration',steps:['Slice the strip and pin upright using your normal profile.','Test holes in order from +0.1 through +0.5 mm; labels are listed in shape names.','Record the successful fit in Print → Fit calibration.'],printNote:'Labels are not embossed. Mark the strip before removing it from the plate.'},
 {id:'washer',name:'Washer / spacer',description:'A flat ring for experimenting with a stand-off or spacer.',learn:'Set an outer diameter, inner diameter and height.',category:'Hardware',level:'Beginner',dimensions:'30 mm outer · 8 mm bore · 5 mm high',tags:'ring stand off bolt spacer washer',steps:['Change the outer cylinder radius and height.','Set the cutter radius to half your desired bore diameter.','Use a fit coupon if the ring must slide onto another part.'],printNote:'Print flat. Load-bearing performance and heat resistance are untested.'},
 {id:'tray',name:'Small parts tray',description:'An open tray for sorting screws and small components.',learn:'Change the overall size while preserving a floor and walls.',category:'Organization',level:'Beginner',dimensions:'80 × 60 × 15 mm · 2 mm wall',tags:'organizer bin storage screws desktop',steps:['Select the outer box to resize the tray.','Update the cavity to preserve wall and floor thickness.','Keep the flat base on the plate and inspect the first layer.'],printNote:'Print open-side up. Check local walls in the slicer after editing.'},
 {id:'cable-guide',name:'Cable pass-through plate',description:'A small plate with three round cable openings.',learn:'Change hole spacing and diameter using editable cutters.',category:'Organization',level:'Beginner',dimensions:'60 × 20 × 4 mm · three 6 mm holes',tags:'cable guide wires holes desk routing',steps:['Set each hole radius to half your desired opening diameter.','Move the hole cutters along X to change spacing.','Print flat and remove sharp edges before routing a cable.'],printNote:'Test the cable opening and finish. This is not an electrical insulator specification.'},
]
export function findTemplates(query:string,category='All'){
 const words=query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean)
 return templateCatalog.filter(item=>(category==='All'||item.category===category)&&words.every(word=>`${item.name} ${item.description} ${item.tags} ${item.category}`.toLocaleLowerCase().includes(word)))
}
